import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * The schema (PRD §13). Written by hand because the Python media worker shares
 * these tables: names, types and constraints are a cross-runtime contract.
 *
 * Primary keys are bigint identities named after their table (`video_id`,
 * `candidate_id`, …), GENERATED BY DEFAULT so a data import can supply ids.
 */
export class Init1789040000000 implements MigrationInterface {
  name = 'Init1789040000000';

  public async up(q: QueryRunner): Promise<void> {
    await q.query(`
      CREATE TABLE "users" (
        "user_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "email" text NOT NULL,
        "password_hash" text NOT NULL,
        "display_name" text,
        "plan" text NOT NULL DEFAULT 'free',
        "limits" jsonb,
        "password_changed_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "users_pkey" PRIMARY KEY ("user_id"),
        CONSTRAINT "users_email_key" UNIQUE ("email")
      )`);

    // Only the SHA-256 of a reset token is stored, so reading this table cannot
    // reset an account; the plaintext exists only in the email.
    await q.query(`
      CREATE TABLE "password_reset_tokens" (
        "password_reset_token_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "token_hash" text NOT NULL,
        "expires_at" timestamptz(3) NOT NULL,
        "used_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("password_reset_token_id"),
        CONSTRAINT "password_reset_tokens_token_hash_key" UNIQUE ("token_hash")
      )`);
    await q.query(`CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens" ("user_id")`);
    await q.query(`CREATE INDEX "password_reset_tokens_expires_at_idx" ON "password_reset_tokens" ("expires_at")`);

    await q.query(`
      CREATE TABLE "videos" (
        "video_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "source_type" text NOT NULL,
        "source_url" text,
        "source_provider" text,
        "object_key" text,
        "original_filename" text NOT NULL,
        "title" text NOT NULL,
        "content_type" text,
        "size_bytes" bigint,
        "duration_ms" integer,
        "width" integer,
        "height" integer,
        "fps" double precision,
        "orientation" text,
        "has_audio" boolean,
        "video_codec" text,
        "audio_codec" text,
        "container" text,
        "language" text,
        "status" text NOT NULL DEFAULT 'CREATED',
        "progress" integer NOT NULL DEFAULT 0,
        "stage" text,
        "substage" text,
        "pipeline_version" text NOT NULL,
        "processing_run" integer NOT NULL DEFAULT 0,
        "analysis_run" integer NOT NULL DEFAULT 0,
        "error_code" text,
        "error_message" text,
        "error_retryable" boolean,
        "error_correlation_id" text,
        "failed_stage" text,
        "thumbnail_key" text,
        "proxy_key" text,
        "audio_key" text,
        "upload_id" text,
        "upload_completed_at" timestamptz(3),
        "rights_confirmed_at" timestamptz(3) NOT NULL,
        "active_transcript_id" bigint,
        "ready_at" timestamptz(3),
        "source_expired_at" timestamptz(3),
        "deleted_at" timestamptz(3),
        "purged_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "videos_pkey" PRIMARY KEY ("video_id"),
        CONSTRAINT "videos_active_transcript_id_key" UNIQUE ("active_transcript_id"),
        CONSTRAINT "videos_status_check" CHECK ("status" IN ('CREATED','UPLOADING','QUEUED','INGESTING','TRANSCRIBING','ANALYZING','READY','FAILED')),
        CONSTRAINT "videos_source_type_check" CHECK ("source_type" IN ('upload','url')),
        CONSTRAINT "videos_progress_check" CHECK ("progress" BETWEEN 0 AND 100),
        CONSTRAINT "videos_duration_check" CHECK ("duration_ms" IS NULL OR "duration_ms" >= 0)
      )`);
    await q.query(`CREATE INDEX "videos_user_id_created_at_idx" ON "videos" ("user_id", "created_at" DESC)`);
    await q.query(`CREATE INDEX "videos_status_idx" ON "videos" ("status")`);

    await q.query(`
      CREATE TABLE "transcripts" (
        "transcript_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "video_id" bigint NOT NULL,
        "version" integer NOT NULL,
        "provider" text NOT NULL,
        "language" text,
        "full_text" text NOT NULL DEFAULT '',
        "segments" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "words" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "word_count" integer NOT NULL DEFAULT 0,
        "duration_ms" integer,
        "provider_job_id" text,
        "provider_metadata" jsonb,
        "status" text NOT NULL DEFAULT 'PENDING',
        "error_code" text,
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "transcripts_pkey" PRIMARY KEY ("transcript_id"),
        CONSTRAINT "transcripts_video_id_version_key" UNIQUE ("video_id", "version"),
        CONSTRAINT "transcripts_status_check" CHECK ("status" IN ('PENDING','PROCESSING','COMPLETED','FAILED'))
      )`);

    await q.query(`
      CREATE TABLE "candidates" (
        "candidate_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "video_id" bigint NOT NULL,
        "transcript_id" bigint,
        "start_ms" integer NOT NULL,
        "end_ms" integer NOT NULL,
        "title" text NOT NULL,
        "hook_text" text NOT NULL,
        "excerpt" text NOT NULL,
        "summary" text NOT NULL,
        "reason" text NOT NULL,
        "category" text NOT NULL,
        "score" integer NOT NULL,
        "component_scores" jsonb NOT NULL,
        "analysis_version" text NOT NULL,
        "analysis_run" integer NOT NULL,
        "provider" text,
        "rank" integer NOT NULL,
        "superseded_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "candidates_pkey" PRIMARY KEY ("candidate_id"),
        CONSTRAINT "candidates_range_check" CHECK ("start_ms" >= 0 AND "start_ms" < "end_ms"),
        CONSTRAINT "candidates_score_check" CHECK ("score" BETWEEN 0 AND 100),
        CONSTRAINT "candidates_category_check" CHECK ("category" IN ('insight','story','humor','controversy','advice','reaction','other'))
      )`);
    await q.query(`CREATE INDEX "candidates_video_id_superseded_at_score_idx" ON "candidates" ("video_id", "superseded_at", "score")`);

    await q.query(`
      CREATE TABLE "renders" (
        "render_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "video_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        "candidate_id" bigint,
        "parent_render_id" bigint,
        "lineage_key" text NOT NULL,
        "version" integer NOT NULL,
        "is_latest" boolean NOT NULL DEFAULT true,
        "title" text NOT NULL,
        "start_ms" integer NOT NULL,
        "end_ms" integer NOT NULL,
        "settings" jsonb NOT NULL,
        "settings_hash" text NOT NULL,
        "pipeline_version" text NOT NULL,
        "status" text NOT NULL DEFAULT 'QUEUED',
        "progress" integer NOT NULL DEFAULT 0,
        "stage" text,
        "substage" text,
        "attempt" integer NOT NULL DEFAULT 1,
        "output_key" text,
        "thumbnail_key" text,
        "width" integer,
        "height" integer,
        "duration_ms" integer,
        "file_size" bigint,
        "framing" jsonb,
        "error_code" text,
        "error_message" text,
        "error_retryable" boolean,
        "error_correlation_id" text,
        "started_at" timestamptz(3),
        "completed_at" timestamptz(3),
        "deleted_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "renders_pkey" PRIMARY KEY ("render_id"),
        CONSTRAINT "renders_lineage_key_version_key" UNIQUE ("lineage_key", "version"),
        CONSTRAINT "renders_status_check" CHECK ("status" IN ('QUEUED','PREPARING','ANALYZING_VISUALS','RENDERING','UPLOADING','COMPLETED','FAILED')),
        CONSTRAINT "renders_range_check" CHECK ("start_ms" >= 0 AND "start_ms" < "end_ms"),
        CONSTRAINT "renders_progress_check" CHECK ("progress" BETWEEN 0 AND 100)
      )`);
    await q.query(`CREATE INDEX "renders_user_id_created_at_idx" ON "renders" ("user_id", "created_at" DESC)`);
    await q.query(`CREATE INDEX "renders_video_id_idx" ON "renders" ("video_id")`);
    await q.query(`CREATE INDEX "renders_settings_hash_idx" ON "renders" ("settings_hash")`);
    await q.query(`CREATE INDEX "renders_lineage_latest_idx" ON "renders" ("lineage_key") WHERE "is_latest"`);

    await q.query(`
      CREATE TABLE "job_runs" (
        "job_run_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "queue_name" text NOT NULL,
        "external_job_id" text NOT NULL,
        "entity_type" text NOT NULL,
        "entity_id" text NOT NULL,
        "attempt" integer NOT NULL,
        "status" text NOT NULL,
        "started_at" timestamptz(3) NOT NULL DEFAULT now(),
        "completed_at" timestamptz(3),
        "duration_ms" integer,
        "error_code" text,
        "error_message" text,
        "metadata" jsonb,
        CONSTRAINT "job_runs_pkey" PRIMARY KEY ("job_run_id"),
        CONSTRAINT "job_runs_queue_job_attempt_key" UNIQUE ("queue_name", "external_job_id", "attempt")
      )`);
    await q.query(`CREATE INDEX "job_runs_entity_idx" ON "job_runs" ("entity_type", "entity_id")`);

    await q.query(`
      CREATE TABLE "usage_events" (
        "usage_event_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "event_type" text NOT NULL,
        "video_id" bigint,
        "render_id" bigint,
        "units" double precision NOT NULL,
        "unit" text NOT NULL,
        "idempotency_key" text NOT NULL,
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "usage_events_pkey" PRIMARY KEY ("usage_event_id"),
        CONSTRAINT "usage_events_idempotency_key_key" UNIQUE ("idempotency_key")
      )`);
    await q.query(`CREATE INDEX "usage_events_user_id_created_at_idx" ON "usage_events" ("user_id", "created_at")`);

    // ------------------------------------------------------------- billing
    // Polar remains the source of truth for billing; this is a local projection
    // kept current by webhooks so the app never calls Polar to render a page.
    await q.query(`
      CREATE TABLE "subscriptions" (
        "subscription_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "polar_subscription_id" text NOT NULL,
        "polar_customer_id" text NOT NULL,
        "polar_product_id" text NOT NULL,
        "plan" text NOT NULL,
        "status" text NOT NULL,
        "recurring_interval" text NOT NULL,
        "amount" integer,
        "currency" text,
        "current_period_start" timestamptz(3),
        "current_period_end" timestamptz(3),
        "cancel_at_period_end" boolean NOT NULL DEFAULT false,
        "started_at" timestamptz(3),
        "ends_at" timestamptz(3),
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("subscription_id"),
        CONSTRAINT "subscriptions_polar_subscription_id_key" UNIQUE ("polar_subscription_id"),
        CONSTRAINT "subscriptions_plan_check" CHECK ("plan" IN ('starter','creator','studio')),
        CONSTRAINT "subscriptions_status_check" CHECK ("status" IN ('active','canceled','past_due','paused')),
        CONSTRAINT "subscriptions_interval_check" CHECK ("recurring_interval" IN ('month','year'))
      )`);
    await q.query(`CREATE INDEX "subscriptions_user_id_idx" ON "subscriptions" ("user_id")`);

    // Two buckets per user: rollover accumulates, expiring is replaced each grant.
    // The CHECK keeps both non-negative.
    await q.query(`
      CREATE TABLE "credit_balances" (
        "credit_balance_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "rollover_credits" integer NOT NULL DEFAULT 0,
        "expiring_credits" integer NOT NULL DEFAULT 0,
        "updated_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "credit_balances_pkey" PRIMARY KEY ("credit_balance_id"),
        CONSTRAINT "credit_balances_user_id_key" UNIQUE ("user_id"),
        CONSTRAINT "credit_balances_non_negative" CHECK ("rollover_credits" >= 0 AND "expiring_credits" >= 0)
      )`);

    // Append-only history. The unique idempotency key is what stops an
    // at-least-once webhook redelivery from granting the same allowance twice.
    await q.query(`
      CREATE TABLE "credit_ledger_entries" (
        "credit_ledger_entry_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "reason" text NOT NULL,
        "rollover_delta" integer NOT NULL,
        "expiring_delta" integer NOT NULL,
        "rollover_after" integer NOT NULL,
        "expiring_after" integer NOT NULL,
        "idempotency_key" text NOT NULL,
        "metadata" jsonb,
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "credit_ledger_entries_pkey" PRIMARY KEY ("credit_ledger_entry_id"),
        CONSTRAINT "credit_ledger_entries_idempotency_key_key" UNIQUE ("idempotency_key"),
        CONSTRAINT "credit_ledger_entries_reason_check" CHECK ("reason" IN ('grant','spend','refund','adjustment'))
      )`);
    await q.query(
      `CREATE INDEX "credit_ledger_entries_user_id_created_at_idx" ON "credit_ledger_entries" ("user_id", "created_at")`,
    );

    // The outer idempotency guard: every delivery we have already handled.
    await q.query(`
      CREATE TABLE "processed_webhooks" (
        "processed_webhook_id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "provider" text NOT NULL,
        "event_id" text NOT NULL,
        "event_type" text NOT NULL,
        "created_at" timestamptz(3) NOT NULL DEFAULT now(),
        CONSTRAINT "processed_webhooks_pkey" PRIMARY KEY ("processed_webhook_id"),
        CONSTRAINT "processed_webhooks_provider_event_key" UNIQUE ("provider", "event_id")
      )`);

    // Deleting a video cascades to its transcripts, candidates and renders (PRD §13.1).
    await q.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "videos" ADD CONSTRAINT "videos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "transcripts" ADD CONSTRAINT "transcripts_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("video_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "videos" ADD CONSTRAINT "videos_active_transcript_id_fkey" FOREIGN KEY ("active_transcript_id") REFERENCES "transcripts"("transcript_id") ON DELETE SET NULL`);
    await q.query(`ALTER TABLE "candidates" ADD CONSTRAINT "candidates_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("video_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "candidates" ADD CONSTRAINT "candidates_transcript_id_fkey" FOREIGN KEY ("transcript_id") REFERENCES "transcripts"("transcript_id") ON DELETE SET NULL`);
    await q.query(`ALTER TABLE "renders" ADD CONSTRAINT "renders_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("video_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "renders" ADD CONSTRAINT "renders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "renders" ADD CONSTRAINT "renders_candidate_id_fkey" FOREIGN KEY ("candidate_id") REFERENCES "candidates"("candidate_id") ON DELETE SET NULL`);
    // The usage ledger outlives the content it refers to (billing history).
    await q.query(`ALTER TABLE "usage_events" ADD CONSTRAINT "usage_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "credit_balances" ADD CONSTRAINT "credit_balances_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
    await q.query(`ALTER TABLE "credit_ledger_entries" ADD CONSTRAINT "credit_ledger_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE`);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE IF EXISTS "processed_webhooks"`);
    await q.query(`DROP TABLE IF EXISTS "credit_ledger_entries"`);
    await q.query(`DROP TABLE IF EXISTS "credit_balances"`);
    await q.query(`DROP TABLE IF EXISTS "subscriptions"`);
    await q.query(`DROP TABLE IF EXISTS "usage_events"`);
    await q.query(`DROP TABLE IF EXISTS "job_runs"`);
    await q.query(`DROP TABLE IF EXISTS "renders"`);
    await q.query(`DROP TABLE IF EXISTS "candidates"`);
    await q.query(`ALTER TABLE "videos" DROP CONSTRAINT IF EXISTS "videos_active_transcript_id_fkey"`);
    await q.query(`DROP TABLE IF EXISTS "transcripts"`);
    await q.query(`DROP TABLE IF EXISTS "videos"`);
    await q.query(`DROP TABLE IF EXISTS "password_reset_tokens"`);
    await q.query(`DROP TABLE IF EXISTS "users"`);
  }
}
